=begin

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

# Problem
- Given two strings, str and new_str
- new_str is formed by shuffling str and then add a new character
- Find an return the new character added
- Input: two strings
- Output: string

# Algorithm
- Sort both strings in alphabetical order
- Iterate through `new_str` (the longer one) with index
  - return the current character if they are different at the current index position

=end

def find_the_difference(s, t)
  s_sort = s.chars.sort
  t_sort = t.chars.sort

  t_sort.each_with_index do |char, index|
    return char if s_sort[index] != t_sort[index]
  end

  nil
end

p find_the_difference('abcd', 'abcde') == 'e'
p find_the_difference('', 'y') == 'y'
